### ISSUE TITLE
Using `if-exists=skip` and `silent=false` in `/note/create` does not open the note in obsidian.

### ISSUE THREAD

**Issue by kartikay-bagla** [czottmann/obsidian-actions-uri#99]
Steps to reproduce:
- Create note in obsidian called `abc` and close the window with `abc`
- Call `obsidian://actions-uri/note/create?vault=vaultname&file=abc&if-exists=skip&silent=false`

It will focus the obsidian window but not open `abc`.

Checking console logs shows

```
...
processedFilepath: undefined
... 
openResult: 
  isSuccess: true
  processedFilepath: undefined
  result: "No file to open, handler didn't return a `processedFilepath`"
```

<img width="529" alt="Image" src="https://github.com/user-attachments/assets/e33fc6cd-8718-46a3-b207-08998e7970da" />

I can tell from the code that in `/src/routes/note/create.ts:169`, the function `_handleCreateNoteFromContent` is being called. But I don't know enough TS to debug further.
